---
- name: create prometheus folder
  ansible.builtin.file:
    path: "{{ prometheus_path }}"
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory

- name: install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.37.3/prometheus-2.37.3.linux-amd64.tar.gz
    dest: "{{ prometheus_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: configure prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_path }}/prometheus.yml"
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
    backup: true

- name: set systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0755
    owner: "{{ user }}"
    group: "{{ group }}"
    backup: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: start prometheus service
  ansible.builtin.systemd:
    service: prometheus
    state: started
